#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cscope
Version  : 15.9
Release  : 11
URL      : https://sourceforge.net/projects/cscope/files/cscope/v15.9/cscope-15.9.tar.gz
Source0  : https://sourceforge.net/projects/cscope/files/cscope/v15.9/cscope-15.9.tar.gz
Summary  : cscope is an interactive, screen-oriented tool that allows the user to browse through C source files for specified elements of code.
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: cscope-bin = %{version}-%{release}
Requires: cscope-license = %{version}-%{release}
Requires: cscope-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(ncurses)

%description
cscope is an interactive, screen-oriented tool that allows the user to browse through C source files for specified elements of code.

%package bin
Summary: bin components for the cscope package.
Group: Binaries
Requires: cscope-license = %{version}-%{release}

%description bin
bin components for the cscope package.


%package license
Summary: license components for the cscope package.
Group: Default

%description license
license components for the cscope package.


%package man
Summary: man components for the cscope package.
Group: Default

%description man
man components for the cscope package.


%prep
%setup -q -n cscope-15.9
cd %{_builddir}/cscope-15.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604539170
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604539170
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cscope
cp %{_builddir}/cscope-15.9/COPYING %{buildroot}/usr/share/package-licenses/cscope/b22fb8b12914337c9e8b231f38040aa13c2b2b92
cp %{_builddir}/cscope-15.9/contrib/webcscope/LICENSE %{buildroot}/usr/share/package-licenses/cscope/0b184ad51ba2a79e85d2288d5fcf8a1ea0481ea4
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cscope
/usr/bin/ocs

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cscope/0b184ad51ba2a79e85d2288d5fcf8a1ea0481ea4
/usr/share/package-licenses/cscope/b22fb8b12914337c9e8b231f38040aa13c2b2b92

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cscope.1
