#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cscope
Version  : 15.9
Release  : 9
URL      : https://sourceforge.net/projects/cscope/files/cscope/v15.9/cscope-15.9.tar.gz
Source0  : https://sourceforge.net/projects/cscope/files/cscope/v15.9/cscope-15.9.tar.gz
Summary  : cscope is an interactive, screen-oriented tool that allows the user to browse through C source files for specified elements of code.
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: cscope-bin
Requires: cscope-license
Requires: cscope-man
BuildRequires : bison
BuildRequires : flex
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(ncurses)

%description
cscope is an interactive, screen-oriented tool that allows the user to browse through C source files for specified elements of code.

%package bin
Summary: bin components for the cscope package.
Group: Binaries
Requires: cscope-license
Requires: cscope-man

%description bin
bin components for the cscope package.


%package license
Summary: license components for the cscope package.
Group: Default

%description license
license components for the cscope package.


%package man
Summary: man components for the cscope package.
Group: Default

%description man
man components for the cscope package.


%prep
%setup -q -n cscope-15.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533050512
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533050512
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/cscope
cp COPYING %{buildroot}/usr/share/doc/cscope/COPYING
cp contrib/webcscope/LICENSE %{buildroot}/usr/share/doc/cscope/contrib_webcscope_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cscope
/usr/bin/ocs

%files license
%defattr(-,root,root,-)
/usr/share/doc/cscope/COPYING
/usr/share/doc/cscope/contrib_webcscope_LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/cscope.1
